### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mariospapaz** [mariospapaz/nvim#1]
- [x] turn off perl provider
- [x] fix mysterious sql highlights error 
- [x] fixed borked libraries
- [x] which-key not opening with leader key press
- [x] leader key buggy due to double imports
- [x] fix alpha for some reason not showing up
- [x] Fix Space key issue
- [x] Update which-key will all keybinds
- [x] Make Documentation about the keybinds
- [x] Add Toggle Term
- [x] Put Toggle Term in which-key
- [x] Change Colorscheme
- [x] Add LuaLine
- [x] tabout is borked
- [x] add bufferline
- [x] fixed command() missing
- [x] add null-ls
- [x] remove non working presence logo
- [x] fix damn sumneko_lua/pyright not loading correctly 
- [x] Put all LSP files in a LSP directory
- [x] remove bloat TS "all" and write only the languages I use
- [x] Make LSP reliable
- [x] install gitsigns
- [x] add Code Actions 
- [x] DiagnosticsErrors emojis not working
- [ ] Standby

**Comment by mariospapaz** [comment]
26-8-21 Neovim Repo will be on hiatus for a month.
